version: '3.3'
services:
  agent:
    container_name: echo_agent
    build: ./
    command: /bin/sh run.sh
    stdin_open: true
    tty: true
    network_mode: host
    depends_on:
      - redis
    restart: always

  redis:
    container_name: echo_agent_redis
    image: redis:alpine
    network_mode: host
    restart: always
