services:
  agent:
    container_name: echo_agent
    build: ./
    command: uvicorn echo_agent.app:app --host 0.0.0.0 --port 11007
    stdin_open: true
    tty: true
    network_mode: host
    restart: always
